#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     hi,             sensorI2CMuxController)
#pragma config(Sensor, S2,     liftFront,      sensorTouch)
#pragma config(Sensor, S3,     liftBack,       sensorTouch)
#pragma config(Sensor, S4,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  motorA,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          l,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Must be here to start corectly in the comp
#include "hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"

//----------------------------------------------Encoder code
const float ticksCm = 1440.0/27.0;//Setting up variables
const float ticksDg = 1450.0/90.0;
const float powerDif = 0.855;

bool onRamp = false;
string t = "Press btn on ramp";

//Drive forward number of cm's
void drive(float cm, float power) //Distance, Power
{
	long ticks = cm*ticksCm;//Converts cm to encoder counts
	nMotorEncoder[left]=0;//Reset encoder

	while(abs (nMotorEncoder[left]) < ticks)//Runs while current encoder counts is less than target
		{
			motor[left]=power;//Runs motors at set power
			motor[right]=power*powerDif;
		}
	motor[left]=0;//Turns off both motors
	motor[right]=0;

	wait1Msec(100);//Short wait to help prevent errors
}

//Turn number of degrees
void turn(float deg, float power) //Degrees, Power (positive is right turn)
{
	long ticks = deg*ticksDg;//Converts degrees to encoder counts
	nMotorEncoder[left]=0;//Reset encoder

	while(abs (nMotorEncoder[left]) < ticks)//Runs while current encoder counts is less than target
		{
			motor[left]=power;//Runs motors at set power
			motor[right]=-power*powerDif;
		}
	motor[left]=0;//Turns off both motors
	motor[right]=0;

	wait1Msec(100);//Short wait to help prevent errors
}

//Raise Lift
void raiseLift(float tm, float power)
{
	motor[lift]=power;//Turns on motor at set power
	wait1Msec(tm);//Waits for set time
	motor[lift]=0;//Turns off motor
}

//Resets lift
void resetLift()
{
	while(SensorValue[liftBack] == 0)//Runs while back botton is not pressed
		{
			motor[lift]=-10;//Turns on motor
		}
	motor[lift]=0;//Turns off motor
}
//---------
//----------------------------------------------End encoder code

task main()
{
	resetLift();//Resets lift then waits for a second
	wait1Msec(1000);

	unsigned long begin = nSysTime + 5000;//Sets up timer for button press

	while(begin > nSysTime)//Runs while time is less than end time
		{
			nxtDisplayTextLine(1, t);//Displays Question
			string b = SensorValue[liftFront];//Writes current value of button does not set if it is on the ramp

			StringFormat( b, "On ramp: %i", SensorValue[liftFront]);//Formats string
			nxtDisplayTextLine(2, b);//Displays value of button

			if (SensorValue[liftFront]==1)//Detects if the robot is on the ramp if button is pressed
				{
					onRamp = true;
				}else //If robot is not on ramp
					{
						onRamp = false;
					}
		}

	string b = SensorValue[liftFront];//Writes current value of button does not set if it is on the ramp

	StringFormat( b, "On ramp: %i", SensorValue[liftFront]);//Formats string
	nxtDisplayTextLine(1, b);//Displays value of button
	nxtDisplayTextLine(2,"Set");//Displays message: set

	wait1Msec(1000);//Waits a second



	//Wait for start of game
	waitForStart();		//Must be here to start corectly in the comp. If needed comment it out so it doesn't wait

	//Game code here
	if(onRamp==true)//Robot is on the ramp
		{
			drive(250,20);//Drives forward to goal
			raiseLift(3000,100);//Raises lift

			servo[servo1]=0;//Starts the servo
			wait1Msec(750);//Waits for 3/4 a second
			servo[servo1]=127;//Turns off servo

			resetLift();//Resets lift

		}else//Robot is on the ground(Going for pole)
			{
				int _dirAC = 0;//Resets IR

				//Navigating to IR becan
				drive(50,30);//Drives forward 50cm
				turn(90,30);//turns right 90 degrees

				drive(100,30);//Drives forward 100cm
				turn(90,-30);//Turns left 90 degrees
				drive(80,30);//Drives forward 80cm

				turn(90,30);//Turns right 90 degrees
				turn(90,30);//Turns right 90 degrees
				turn(100,30);//Turns right 100 degrees (100 to fix not being 100% accurate)

				drive(62,30);//Drives forwards 62cm up to the becan
				//At IR becan

				wait1Msec(1000);//waits to let IR get a good read
				_dirAC = HTIRS2readACDir(HTIRS2);//Reads IR value

				if(_dirAC<9 && _dirAC>6)//If beacon is facing robot
					{
						drive(60,-30);//Drives backwards 60cm
						turn(80,30);//Turns right 80 degrees
						drive(20,30);//Drives forward 20cm
						turn(35,35);//Knocks pole down by turning
					}
				if(_dirAC<7 && _dirAC>4)//If beacon is facing the corner
					{
						drive(50,-30);//Drives backwards 50cm
						turn(80,30);//Turns right 80 degrees
						drive(5,30);//Drives forward 5cm
						turn(45,35);//Knocks pole down by turning
						drive(35,-75);//Backs up to avoid being hit
					}
				if(_dirAC==9 || _dirAC==0)//If pole is facing robot
					{
						drive(60,-30);//Drives backwards 60 cm
						turn(25,30);//Turns right 25 degrees
						drive(35,30);//Drives Forward 35cm
						turn(50,-50);//Knocks pole down by turning
					}
			}
}
