#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     hi,             sensorI2CMuxController)
#pragma config(Sensor, S2,     modeButton,     sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          l,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //Must be here to start corectly in the comp
#include "Encoder.c"

const float ticksCm = 1440.0/27.0;
const float ticksDg = 1625.0/90.0;
const float powerDif = 0.85;

//Drive forward number of cm's
void driveDistance(float cm, float power) //Distance, Power
{
	long ticks = cm*ticksCm;
	nMotorEncoder[left]=0;
	while(abs (nMotorEncoder[left]) < ticks)
		{
			motor[left]=power;
			motor[right]=power*powerDif;
		}
	motor[left]=0;
	motor[right]=0;
	wait10Msec(10);
}

//Turn number of degrees
void turn(float deg, float power) //Degrees, Power (positive is right turn)
{
	long ticks = deg*ticksDg;
	nMotorEncoder[left]=0;
	while(abs (nMotorEncoder[left]) < ticks)
		{
			motor[left]=power;
			motor[right]=-power*powerDif;
		}
	motor[left]=0;
	motor[right]=0;
	wait10Msec(10);
}
//----------------------------------------------

//----------------------------------------------

bool onRamp;

task main()
{
	//Detects if the robot is on the ramp if button is pressed
	if (SensorValue[modeButton]==1)
		{
			onRamp = true;
		}else
			{
				onRamp = false;
			}

	//Before game reset code here


	//Wait for start of game
	waitForStart();		//Must be here to start corectly in the comp. If needed comment it out so it doesn't wait

	//Game code here
	if(onRamp==true)
		{
			//Code here for if robobot starts on the ramp

		}else
			{
				//Code here for if robobot starts on the ground
				driveDistance(120,20);

				if(SensorValue[IR]>5.1 && SensorValue[IR]<4.9)//If IR is directly ahead
					{
						turn(90,20);
						driveDistance(30,20);
						turn(90,-20);
						driveDistance(90,50);

					}else if(SensorValue[IR]<4.5 && SensorValue[IR]>2)//If center is at an angle
						{
							turn(45,20)
							driveDistance(90,50);

						}else//If the bar is facing the robot
							{
								turn(90,-20);
								driveDistance(60,20);
								turn(90,20);
								driveDistance(30,20);
								turn(90,20);
								driveDistance(90,50);

							}
			}
}
