#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     hi,             sensorNone)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     modeButton,     sensorTouch)
#pragma config(Motor,  motorA,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          l,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "JoystickDriver.c" //Must be here to start corectly in the comp
#include "hitechnic-irseeker-v2.h"

const float ticksCm = 1440.0/27.0;
const float ticksDg = 1430.0/90.0;
const float powerDif = 0.85;

//Drive forward number of cm's
void drive(float cm, float power) //Distance, Power
{
	long ticks = cm*ticksCm;
	nMotorEncoder[left]=0;
	while(abs (nMotorEncoder[left]) < ticks)
		{
			motor[left]=power;
			motor[right]=power*powerDif;
		}
	motor[left]=0;
	motor[right]=0;
	wait10Msec(10);
}

//Turn number of degrees
void turn(float deg, float power) //Degrees, Power (positive is right turn)
{
	long ticks = deg*ticksDg;
	nMotorEncoder[left]=0;
	while(abs (nMotorEncoder[left]) < ticks)
		{
			motor[left]=power;
			motor[right]=-power*powerDif;
		}
	motor[left]=0;
	motor[right]=0;
	wait10Msec(10);
}

//----------------------------------------------

bool onRamp = false;
string t = "Press btn on ramp";

task main()
{
	wait10Msec(100);
	unsigned long begin = nSysTime + 5000;

	while(begin > nSysTime)
		{
			nxtDisplayTextLine(1, t);
			string b = SensorValue[modeButton];
			StringFormat( b, "On ramp: %i", SensorValue[modeButton]);
			nxtDisplayTextLine(2, b);

			if (SensorValue[modeButton]==1)//Detects if the robot is on the ramp if button is pressed
				{
					onRamp = true;
				}else
					{
						onRamp = false;
					}
		}

	string b = SensorValue[modeButton];
	StringFormat( b, "On ramp: %i", SensorValue[modeButton]);
	nxtDisplayTextLine(2, b);

	nxtDisplayTextLine(1, b);
	nxtDisplayTextLine(2,"");

	wait10Msec(1000);
	//Before game reset code here


	//Wait for start of game
	//waitForStart();		//Must be here to start corectly in the comp. If needed comment it out so it doesn't wait

	//Game code here
	if(onRamp==true)//Robot is on the ramp
		{
			drive(225,20);
			//Dispence Ball
			wait10Msec(100);
			turn(90,-20);

		}else//Robot is on the ground
			{
				int _dirAC = 0;//Resets IR

				drive(130,20);//Drives Forward
				turn(100,-20);//Turns left
				drive(40,-20);//Drives Backwards

				wait10Msec(50);
				_dirAC = HTIRS2readACDir(HTIRS2);//wairs for 0.5 a second then reads IR

				if(_dirAC>7)//If beacon is facing robot
					{
						drive(30,-20);//Drives Backwards
						turn(90,20);//Turns right
						drive(50,20);//Drives Forward
						turn(35,20);//Knocks pole down by turning
					}
				if(_dirAC==7)//If beacon is facing the corner
					{
						drive(50,-20);//Drives Backwards
						turn(55,20);//Turns right
						drive(40,20);//Drives Forward
						turn(45,25);//Knocks pole down by turning
					}
				if(_dirAC==0)//If pole is facing robot
					{
						turn(5,20);//Turns right
						drive(90,20);//Drives Forward
						turn(90,20);//Turns right
						drive(20,20);//Drives Forward
						turn(90,20);//Turns right
						drive(55,20);//Drives Forward
						turn(45,25);//Knocks pole down by turning
					}

					_dirAC = HTIRS2readACDir(HTIRS2);
					string t;
					StringFormat( t, "Sensor Value: %i", _dirAC);
					//string t = "Sensor Value:" + _dirAC;
					nxtDisplayTextLine(1, t);

					wait10Msec(100);
			}
}
