#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     hi,             sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,              sensorI2CCustom)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          l,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"

const float ticksCm = 1440.0/27.0;
const float ticksDg = 1450.0/90.0;
const float powerDif = 0.80;

//Drive forward number of cm's
void drive(float cm, float power) //Distance, Power
{
	long ticks = cm*ticksCm;
	nMotorEncoder[left]=0;
	while(abs (nMotorEncoder[left]) < ticks)
		{
			motor[left]=power;
			motor[right]=power*powerDif;
		}
	motor[left]=0;
	motor[right]=0;
	wait10Msec(10);
}

//Turn number of degrees
void turn(float deg, float power) //Degrees, Power (positive is right turn)
{
	long ticks = deg*ticksDg;
	nMotorEncoder[left]=0;
	while(abs (nMotorEncoder[left]) < ticks)
		{
			motor[left]=power;
			motor[right]=-power*powerDif;
		}
	motor[left]=0;
	motor[right]=0;
	wait10Msec(10);
}

//---------

task main()
{
	int _dirAC = 0;

	drive(65,20);
	turn(52,-10);
	wait10Msec(100);
	_dirAC = HTIRS2readACDir(HTIRS2);

	if(_dirAC==6)
		{

			nxtDisplayTextLine(2, "Ahead");

		}else
			{
				drive(60,20);
				turn(30,-20);
				if(_dirAC==0)
					{

						nxtDisplayTextLine(2, "Slanted");

					}else
						{
							nxtDisplayTextLine(2, "Pole Ahead");

						}
			}
			while(true)
				{
					_dirAC = HTIRS2readACDir(HTIRS2);
					string t = _dirAC;
					nxtDisplayTextLine(1, t);

				}
}
