#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     hi,             sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          l,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{

//	waitForStart();
	while(true)
		{
			getJoystickSettings(joystick);

			if(joystick.joy1_y1<5 && joystick.joy1_y1>-5)
				{
					motor[right]=0;
				}else
					{
						float RWheel = (float)joystick.joy1_y1/128*100;
						motor[right]=(short)RWheel;
					}

			if(joystick.joy1_y2<5 && joystick.joy1_y2>-5)
				{
					motor[left]=0;
				}else
					{
						float LWheel = (float )joystick.joy1_y2/128.0*100.0;
						motor[left]=(short)LWheel;
					}

			//Buttons X A B Y

			if(joy1Btn(1) == 1)		//If X button is pressed
				{

				}else
					{

					}

			if(joy1Btn(2) == 1)		//If A button is pressed
				{

				}else
					{

					}

			if(joy1Btn(3) == 1)		//If B buttom is pressed
				{

				}else
					{

					}

			if(joy1Btn(4) == 1)		//If Y buttom is pressed
				{

				}else
					{

					}


			//Trigger buttons

			if(joy1Btn(8) == 1)		//If Left Trigger button is pressed
				{

				}else
					{

					}

			if(joy1Btn(7) == 1)		//If Right Trigger button is pressed
				{

				}else
					{

					}

			if(joy1Btn(06) == 1)		//If Left Top Trigger button is pressed
				{
					motor[arm]=100;
				}else
					{
						motor[arm]=0;
					}

			if(joy1Btn(05) == 1)		//If Right Top Trigger button is pressed
				{

				}else
					{

					}


		}


}
