#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     hi,             sensorI2CMuxController)
#pragma config(Sensor, S2,     liftFront,      sensorTouch)
#pragma config(Sensor, S3,     liftBack,       sensorTouch)
#pragma config(Sensor, S4,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  motorA,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          l,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    sweeper,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"		//Must be here to start corectly in the comp

bool liftUp=false;
bool liftDown=false;
float factor=1;

task main()
{

	//waitForStart();		//Must be here to start corectly in the comp. If needed comment it out so it doesn't wait
	while(true)
		{
			if(SensorValue[liftFront]==1)
				{
					liftUp=true;
					motor[lift]=-10;
					wait1Msec(10);
					motor[lift]=0;
				}
				if(SensorValue[liftBack]==1)
				{
					liftDown=true;
					motor[lift]=0;
				}

			getJoystickSettings(joystick);

			if(joystick.joy2_y1<5 && joystick.joy2_y1>-5)
				{
					motor[right]=0;
				}else
					{
						float RWheel = ((float )joystick.joy1_y1/128.0*100.0)*factor;
						motor[right]=(short)RWheel;
					}

			if(joystick.joy1_y2<5 && joystick.joy1_y2>-5)
				{
					motor[left]=0;
				}else
					{
						float LWheel = ((float )joystick.joy1_y2/128.0*100.0)*factor;
						motor[left]=(short)LWheel;
					}

			//Buttons X A B Y

			if(joy1Btn(1) == 1)		//If X button is pressed
				{
					factor=0.66;
				}else
					{

					}

			if(joy1Btn(2) == 1)		//If A button is pressed
				{
					factor=0.33;
				}else
					{

					}

			if(joy1Btn(3) == 1)		//If B buttom is pressed
				{

				}else
					{

					}

			if(joy1Btn(4) == 1)		//If Y buttom is pressed
				{
					factor=1;
				}else
					{

					}


			//Trigger buttons

			if(joy1Btn(8) == 1)		//If Left Trigger button is pressed
				{

				}else
					{

					}

			if(joy1Btn(7) == 1)		//If Right Trigger button is pressed
				{

				}else
					{

					}

			if(joy1Btn(06) == 1)		//If Left Top Trigger button is pressed
				{

				}else
					{

					}

			if(joy1Btn(05) == 1)		//If Right Top Trigger button is pressed
				{

				}else
					{

					}

			//Joy Stick 2
			getJoystickSettings(joystick);

			if(joystick.joy1_y1<5 && joystick.joy1_y1>-5)
				{
					motor[lift]=0;
				}else
					{
						float RWheel = ((float)joystick.joy1_y1/128*100)+10;
						if(liftUp==true)
							{
								if(joystick.joy1_y1 < -10)
									{
										liftUp=false;
									}
								if(liftUp==false)
									{
										motor[lift]=(short)RWheel;
									}
							}else if(liftDown==true)
								{
									if(joystick.joy1_y1 > 10)
										{
											liftDown=false;
										}
									if(liftDown==false)
										{
											motor[lift]=(short)RWheel;
										}
								}else
									{
										motor[lift]=(short)RWheel;
									}



					}

			if(joystick.joy2_y2<5 && joystick.joy2_y2>-5)
				{

				}else
					{

					}

			//Buttons X A B Y

			if(joy2Btn(1) == 1)		//If X button is pressed
				{

				}else
					{

					}

			if(joy2Btn(2) == 1)		//If A button is pressed
				{

				}else
					{

					}

			if(joy2Btn(3) == 1)		//If B buttom is pressed
				{

				}else
					{

					}

			if(joy2Btn(4) == 1)		//If Y buttom is pressed
				{

				}else
					{

					}


			//Trigger buttons

			if(joy2Btn(8) == 1)		//If Left Trigger button is pressed
				{
					motor[sweeper]=10;
				}else
					{

					}

			if(joy2Btn(7) == 1)		//If Right Trigger button is pressed
				{

				}else
					{

					}

			if(joy2Btn(06) == 1)		//If Left Top Trigger button is pressed
				{

				}else
					{

					}

			if(joy2Btn(05) == 1)		//If Right Top Trigger button is pressed
				{

				}else
					{

					}
		}


}
