#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     hi,             sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          l,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	waitForStart();
	while(true)
		{
			getJoystickSettings(joystick);

			if(joystick.joy1_y1<5 && joystick.joy1_y1>-5)
				{
					motor[right]=0;
				}else
					{
						motor[right]=joystick.joy1_y1;
					}
			if(joystick.joy1_y2<5 && joystick.joy1_y2>-5)
				{
					motor[left]=0;
				}else
					{
						motor[left]=joystick.joy1_y2;
					}

			//Buttons X A B Y

			if(joy1Btn(1) == 1)		//If X button is pressed
				{
					motor[arm]=100;
				}else
					{
						motor[arm]=0;
					}

			if(joy1Btn(2) == 1)		//If A button is pressed
				{

				}else
					{

					}

			if(joy1Btn(3) == 1)		//If B buttom is pressed
				{

				}else
					{

					}

			if(joy1Btn(4) == 1)		//If Y buttom is pressed
				{

				}else
					{

					}


			//Trigger buttons


		}


}
