#pragma config(Sensor, S1,     button,         sensorTouch)
#pragma config(Sensor, S3,     light,          sensorNone)
#pragma config(Sensor, S4,     sonar,          sensorNone)
#pragma config(Motor,  motorA,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float power = 0;
unsigned long oldTime = 0;

void move(float leftWheel, float rightWheel)
{
	motor[left]=leftWheel;
	motor[right]=rightWheel;
}

void halt()
{
	motor[left]=0;
	motor[right]=0;
}

task touch
{
	while (SensorValue[button] == true)
		{
			if (SensorValue[button] == true)
				{
					move(-100,-100);
					wait10Msec(100);
					halt();
				}
		}
}

task main()
{
StartTask (touch);
while (SensorValue[button] == false)
	{
		if(nSysTime >= oldTime)
			{
				oldTime = nSysTime + 1000;
				power = power + 5;
				move(power,power);
			}
	}
}
