#pragma config(StandardModel, "Virtual Worlds NXT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[motorA] = 100;
wait10Msec(10);
motor[motorA] = 0;

}
