#pragma config(StandardModel, "REMBOT")
#pragma config(RenamedStdModelMotor, motorA, right)
#pragma config(RenamedStdModelMotor, motorB, left)
#pragma config(RenamedStdModelMotor, motorC, arm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[right]=100;
motor[left]=100;
wait10Msec(10);
motor[right]=0;
motor[left]=0;

}
