#pragma config(StandardModel, "REMBOT")
#pragma config(RenamedStdModelMotor, motorA, right)
#pragma config(RenamedStdModelMotor, motorB, left)
#pragma config(RenamedStdModelMotor, motorC, arm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task gun
{
motor[arm]=100;
wait10Msec(50);
motor[arm]=0;
}

void move(float a,//right motor
float b, float t)
{
motor[right]=a;
motor[left]=b;
wait10Msec(t);
motor[right]=0;
motor[left]=0;
}

task main()
{
StartTask (gun);
move (100,100,100);


wait10Msec(100);
move (-100,-100,100);



}
